// This file was generated by counterfeiter
package test

import (
	"github.com/satori/go.uuid"
)

// CreateRandomValidTestName functions creates a valid length name
func CreateRandomValidTestName(name string) string {
	randomName := name + uuid.Must(uuid.NewV4()).String()
	if len(randomName) > 62 {
		return randomName[:61]
	}
	return randomName
}
