name: auth-db
controller: DeploymentConfig

revisionHistoryLimit: 2
triggers:
- type: ConfigChange
strategy:
  rollingParams:
    timeoutSeconds: 7200
  type: Rolling

containers:
- name: auth-db
  image: registry.centos.org/postgresql/postgresql:9.6
  imagePullPolicy: IfNotPresent
  env:
  - name: POSTGRESQL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        key: AUTH_POSTGRES_PASSWORD
        name: auth
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  livenessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host $POD_IP
    failureThreshold: 6
    initialDelaySeconds: 60
    timeoutSeconds: 5
  readinessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host $POD_IP
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 3
  volumeMounts:
  - mountPath: /var/lib/pgsql
    name: auth-db-postgresql-data

services:
- portMappings:
  - 5432
  
volumeClaims:
- name: auth-db-postgresql-data
  size: 1Gi
