// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "wit": codebase Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --notool=true
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-auth/wit
// --pkg=witservice
// --version=v1.2.0

package witservice

import (
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// CheStartCodebasePath computes a request path to the cheStart action of codebase.
func CheStartCodebasePath() string {

	return fmt.Sprintf("/api/codebases/che/start")
}

// Start che server if not running.
func (c *Client) CheStartCodebase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewCheStartCodebaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCheStartCodebaseRequest create the request corresponding to the cheStart action endpoint of the codebase resource.
func (c *Client) NewCheStartCodebaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PATCH", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// CheStateCodebasePath computes a request path to the cheState action of codebase.
func CheStateCodebasePath() string {

	return fmt.Sprintf("/api/codebases/che/state")
}

// Get che server state.
func (c *Client) CheStateCodebase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewCheStateCodebaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCheStateCodebaseRequest create the request corresponding to the cheState action endpoint of the codebase resource.
func (c *Client) NewCheStateCodebaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// CreateCodebasePath computes a request path to the create action of codebase.
func CreateCodebasePath(codebaseID uuid.UUID) string {
	param0 := codebaseID.String()

	return fmt.Sprintf("/api/codebases/%s/create", param0)
}

// Trigger create a worksapce for a codebase.
func (c *Client) CreateCodebase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewCreateCodebaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateCodebaseRequest create the request corresponding to the create action endpoint of the codebase resource.
func (c *Client) NewCreateCodebaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// EditCodebasePath computes a request path to the edit action of codebase.
func EditCodebasePath(codebaseID uuid.UUID) string {
	param0 := codebaseID.String()

	return fmt.Sprintf("/api/codebases/%s/edit", param0)
}

// Trigger edit of a given codebase.
func (c *Client) EditCodebase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewEditCodebaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewEditCodebaseRequest create the request corresponding to the edit action endpoint of the codebase resource.
func (c *Client) NewEditCodebaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// OpenCodebasePath computes a request path to the open action of codebase.
func OpenCodebasePath(codebaseID uuid.UUID, workspaceID string) string {
	param0 := codebaseID.String()
	param1 := workspaceID

	return fmt.Sprintf("/api/codebases/%s/open/%s", param0, param1)
}

// Trigger open of a given worksapce for a codebase.
func (c *Client) OpenCodebase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewOpenCodebaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewOpenCodebaseRequest create the request corresponding to the open action endpoint of the codebase resource.
func (c *Client) NewOpenCodebaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// ShowCodebasePath computes a request path to the show action of codebase.
func ShowCodebasePath(codebaseID uuid.UUID) string {
	param0 := codebaseID.String()

	return fmt.Sprintf("/api/codebases/%s", param0)
}

// Retrieve codebase with given id.
func (c *Client) ShowCodebase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowCodebaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowCodebaseRequest create the request corresponding to the show action endpoint of the codebase resource.
func (c *Client) NewShowCodebaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
