// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "wit": render Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --notool=true
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-auth/wit
// --pkg=witservice
// --version=v1.2.0

package witservice

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// RenderRenderPath computes a request path to the render action of render.
func RenderRenderPath() string {

	return fmt.Sprintf("/api/render")
}

// Render some content using the markup language
func (c *Client) RenderRender(ctx context.Context, path string, payload *MarkupRenderingPayload) (*http.Response, error) {
	req, err := c.NewRenderRenderRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRenderRenderRequest create the request corresponding to the render action endpoint of the render resource.
func (c *Client) NewRenderRenderRequest(ctx context.Context, path string, payload *MarkupRenderingPayload) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}
