// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "wit": work_item_comments Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --notool=true
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-auth/wit
// --pkg=witservice
// --version=v1.2.0

package witservice

import (
	"bytes"
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
	"strconv"
)

// CreateWorkItemCommentsPayload is the work_item_comments create action payload.
type CreateWorkItemCommentsPayload struct {
	Data *CreateComment `form:"data" json:"data" xml:"data"`
	// An array of mixed types
	Included []interface{} `form:"included,omitempty" json:"included,omitempty" xml:"included,omitempty"`
}

// CreateWorkItemCommentsPath computes a request path to the create action of work_item_comments.
func CreateWorkItemCommentsPath(wiID uuid.UUID) string {
	param0 := wiID.String()

	return fmt.Sprintf("/api/workitems/%s/comments", param0)
}

// Creates a comment associated with the given work item
func (c *Client) CreateWorkItemComments(ctx context.Context, path string, payload *CreateWorkItemCommentsPayload) (*http.Response, error) {
	req, err := c.NewCreateWorkItemCommentsRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateWorkItemCommentsRequest create the request corresponding to the create action endpoint of the work_item_comments resource.
func (c *Client) NewCreateWorkItemCommentsRequest(ctx context.Context, path string, payload *CreateWorkItemCommentsPayload) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// ListWorkItemCommentsPath computes a request path to the list action of work_item_comments.
func ListWorkItemCommentsPath(wiID uuid.UUID) string {
	param0 := wiID.String()

	return fmt.Sprintf("/api/workitems/%s/comments", param0)
}

// List comments associated with the given work item
func (c *Client) ListWorkItemComments(ctx context.Context, path string, pageLimit *int, pageOffset *string, ifModifiedSince *string, ifNoneMatch *string) (*http.Response, error) {
	req, err := c.NewListWorkItemCommentsRequest(ctx, path, pageLimit, pageOffset, ifModifiedSince, ifNoneMatch)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListWorkItemCommentsRequest create the request corresponding to the list action endpoint of the work_item_comments resource.
func (c *Client) NewListWorkItemCommentsRequest(ctx context.Context, path string, pageLimit *int, pageOffset *string, ifModifiedSince *string, ifNoneMatch *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if pageLimit != nil {
		tmp13 := strconv.Itoa(*pageLimit)
		values.Set("page[limit]", tmp13)
	}
	if pageOffset != nil {
		values.Set("page[offset]", *pageOffset)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if ifModifiedSince != nil {

		header.Set("If-Modified-Since", *ifModifiedSince)
	}
	if ifNoneMatch != nil {

		header.Set("If-None-Match", *ifNoneMatch)
	}
	return req, nil
}

// RelationsWorkItemCommentsPath computes a request path to the relations action of work_item_comments.
func RelationsWorkItemCommentsPath(wiID uuid.UUID) string {
	param0 := wiID.String()

	return fmt.Sprintf("/api/workitems/%s/relationships/comments", param0)
}

// List comments associated with the given work item
func (c *Client) RelationsWorkItemComments(ctx context.Context, path string, pageLimit *int, pageOffset *string, ifModifiedSince *string, ifNoneMatch *string) (*http.Response, error) {
	req, err := c.NewRelationsWorkItemCommentsRequest(ctx, path, pageLimit, pageOffset, ifModifiedSince, ifNoneMatch)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRelationsWorkItemCommentsRequest create the request corresponding to the relations action endpoint of the work_item_comments resource.
func (c *Client) NewRelationsWorkItemCommentsRequest(ctx context.Context, path string, pageLimit *int, pageOffset *string, ifModifiedSince *string, ifNoneMatch *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if pageLimit != nil {
		tmp14 := strconv.Itoa(*pageLimit)
		values.Set("page[limit]", tmp14)
	}
	if pageOffset != nil {
		values.Set("page[offset]", *pageOffset)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if ifModifiedSince != nil {

		header.Set("If-Modified-Since", *ifModifiedSince)
	}
	if ifNoneMatch != nil {

		header.Set("If-None-Match", *ifNoneMatch)
	}
	return req, nil
}
