// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "wit": work_item_link Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --notool=true
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-auth/wit
// --pkg=witservice
// --version=v1.2.0

package witservice

import (
	"bytes"
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// CreateWorkItemLinkPath computes a request path to the create action of work_item_link.
func CreateWorkItemLinkPath() string {

	return fmt.Sprintf("/api/workitemlinks")
}

// Create a work item link
func (c *Client) CreateWorkItemLink(ctx context.Context, path string, payload *CreateWorkItemLinkPayload) (*http.Response, error) {
	req, err := c.NewCreateWorkItemLinkRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateWorkItemLinkRequest create the request corresponding to the create action endpoint of the work_item_link resource.
func (c *Client) NewCreateWorkItemLinkRequest(ctx context.Context, path string, payload *CreateWorkItemLinkPayload) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// DeleteWorkItemLinkPath computes a request path to the delete action of work_item_link.
func DeleteWorkItemLinkPath(linkID uuid.UUID) string {
	param0 := linkID.String()

	return fmt.Sprintf("/api/workitemlinks/%s", param0)
}

// Delete work item link with given id.
func (c *Client) DeleteWorkItemLink(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteWorkItemLinkRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteWorkItemLinkRequest create the request corresponding to the delete action endpoint of the work_item_link resource.
func (c *Client) NewDeleteWorkItemLinkRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// ShowWorkItemLinkPath computes a request path to the show action of work_item_link.
func ShowWorkItemLinkPath(linkID uuid.UUID) string {
	param0 := linkID.String()

	return fmt.Sprintf("/api/workitemlinks/%s", param0)
}

// Retrieve work item link (as JSONAPI) for the given link ID.
func (c *Client) ShowWorkItemLink(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Response, error) {
	req, err := c.NewShowWorkItemLinkRequest(ctx, path, ifModifiedSince, ifNoneMatch)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowWorkItemLinkRequest create the request corresponding to the show action endpoint of the work_item_link resource.
func (c *Client) NewShowWorkItemLinkRequest(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if ifModifiedSince != nil {

		header.Set("If-Modified-Since", *ifModifiedSince)
	}
	if ifNoneMatch != nil {

		header.Set("If-None-Match", *ifNoneMatch)
	}
	return req, nil
}

// UpdateWorkItemLinkPath computes a request path to the update action of work_item_link.
func UpdateWorkItemLinkPath(linkID uuid.UUID) string {
	param0 := linkID.String()

	return fmt.Sprintf("/api/workitemlinks/%s", param0)
}

// Update the given work item link with given id.
func (c *Client) UpdateWorkItemLink(ctx context.Context, path string, payload *UpdateWorkItemLinkPayload) (*http.Response, error) {
	req, err := c.NewUpdateWorkItemLinkRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUpdateWorkItemLinkRequest create the request corresponding to the update action endpoint of the work_item_link resource.
func (c *Client) NewUpdateWorkItemLinkRequest(ctx context.Context, path string, payload *UpdateWorkItemLinkPayload) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PATCH", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}
