// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "wit": work_item_relationships_links Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --notool=true
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-auth/wit
// --pkg=witservice
// --version=v1.2.0

package witservice

import (
	"bytes"
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// CreateWorkItemRelationshipsLinksPath computes a request path to the create action of work_item_relationships_links.
func CreateWorkItemRelationshipsLinksPath(wiID uuid.UUID) string {
	param0 := wiID.String()

	return fmt.Sprintf("/api/workitems/%s/relationships/links", param0)
}

// Create a work item link
func (c *Client) CreateWorkItemRelationshipsLinks(ctx context.Context, path string, payload *CreateWorkItemLinkPayload) (*http.Response, error) {
	req, err := c.NewCreateWorkItemRelationshipsLinksRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateWorkItemRelationshipsLinksRequest create the request corresponding to the create action endpoint of the work_item_relationships_links resource.
func (c *Client) NewCreateWorkItemRelationshipsLinksRequest(ctx context.Context, path string, payload *CreateWorkItemLinkPayload) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// ListWorkItemRelationshipsLinksPath computes a request path to the list action of work_item_relationships_links.
func ListWorkItemRelationshipsLinksPath(wiID uuid.UUID) string {
	param0 := wiID.String()

	return fmt.Sprintf("/api/workitems/%s/relationships/links", param0)
}

// List work item links associated with the given work item (either as source or as target work item).
func (c *Client) ListWorkItemRelationshipsLinks(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Response, error) {
	req, err := c.NewListWorkItemRelationshipsLinksRequest(ctx, path, ifModifiedSince, ifNoneMatch)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListWorkItemRelationshipsLinksRequest create the request corresponding to the list action endpoint of the work_item_relationships_links resource.
func (c *Client) NewListWorkItemRelationshipsLinksRequest(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if ifModifiedSince != nil {

		header.Set("If-Modified-Since", *ifModifiedSince)
	}
	if ifNoneMatch != nil {

		header.Set("If-None-Match", *ifNoneMatch)
	}
	return req, nil
}
