kind: Template
apiVersion: v1
metadata:
  name: auth
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      service: auth
    name: auth
  spec:
    replicas: 4
    selector:
      service: auth
    strategy:
      resources:
        limits:
          memory: 1.5Gi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: auth
      spec:
        containers:
        - image: registry.devshift.net/fabric8-services/fabric8-auth:${IMAGE_TAG}
          env:
          - name: AUTH_POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: auth
                key: db.host
          - name: AUTH_POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: auth
                key: db.port
          - name: AUTH_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: auth
                key: db.user
          - name: AUTH_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth
                key: db.password
          - name: AUTH_KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                name: auth
                key: keycloak.realm
          - name: AUTH_KEYCLOAK_SECRET
            valueFrom:
              secretKeyRef:
                name: auth
                key: keycloak.secret
          - name: AUTH_SERVICEACCOUNT_PRIVATEKEY
            valueFrom:
              secretKeyRef:
                name: auth
                key: serviceaccount.privatekey
          - name: AUTH_SERVICEACCOUNT_PRIVATEKEYID
            valueFrom:
              secretKeyRef:
                name: auth
                key: serviceaccount.privatekeyid
          - name: AUTH_GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth
                key: github.client.id
          - name: AUTH_GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth
                key: github.client.secret
          - name: AUTH_OSO_CLIENT_APIURL
            valueFrom:
              secretKeyRef:
                name: auth
                key: oso.client.apiurl
          - name: AUTH_OSO_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth
                key: oso.client.id
          - name: AUTH_OSO_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth
                key: oso.client.secret
          - name: AUTH_POSTGRES_SSLMODE
            valueFrom:
              configMapKeyRef:
                name: auth
                key: postgres.sslmode
          - name: AUTH_POSTGRES_CONNECTION_MAXIDLE
            valueFrom:
              configMapKeyRef:
                name: auth
                key: postgres.connection.maxidle
          - name: AUTH_POSTGRES_CONNECTION_MAXOPEN
            valueFrom:
              configMapKeyRef:
                name: auth
                key: postgres.connection.maxopen
          - name: AUTH_NOTAPPROVED_REDIRECT
            valueFrom:
              configMapKeyRef:
                name: auth
                key: notapproved_redirect
          - name: AUTH_REDIRECT_VALID
            valueFrom:
              configMapKeyRef:
                name: auth
                key: redirect.valid
          - name: AUTH_KEYCLOAK_URL
            valueFrom:
              configMapKeyRef:
                name: auth
                key: keycloak.url
          imagePullPolicy: Always
          name: auth
          ports:
          - containerPort: 8089
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8089
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8089
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /etc/auth/serviceaccounts.conf
            subPath: serviceaccounts.conf
            name: configmap-volume
        volumes:
        - name: configmap-volume
          configMap:
            name: auth-serviceaccounts
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    details:
      causes:
      - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: auth
    labels:
      service: auth
  spec:
    ports:
      - name: "8089"
        protocol: TCP
        port: 80
        targetPort: 8089
    selector:
      service: auth
    type: ClusterIP
    sessionAffinity: null
- kind: Route
  apiVersion: v1
  metadata:
    name: auth
  spec:
    host: ''
    to:
      kind: Service
      name: auth
parameters:
- name: IMAGE_TAG
  value: latest
