kind: Template
apiVersion: v1
metadata:
  name: auth
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      service: auth
    name: auth
  spec:
    replicas: ${{REPLICAS}}
    selector:
      service: auth
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: auth
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          env:
          - name: AUTH_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: AUTH_POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: auth
                key: db.host
          - name: AUTH_POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: auth
                key: db.port
          - name: AUTH_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: auth
                key: db.user
          - name: AUTH_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth
                key: db.password
          - name: AUTH_OAUTH_PROVIDER_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth
                key: oauth.provider.client.id
          - name: AUTH_OAUTH_PROVIDER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth
                key: oauth.provider.client.secret
          - name: AUTH_OAUTH_PROVIDER_ENDPOINT_AUTH
            valueFrom:
              configMapKeyRef:
                name: auth
                key: oauth.provider.endpoint.auth
          - name: AUTH_OAUTH_PROVIDER_ENDPOINT_USERINFO
            valueFrom:
              configMapKeyRef:
                name: auth
                key: oauth.provider.endpoint.userinfo
          - name: AUTH_OAUTH_PROVIDER_ENDPOINT_TOKEN
            valueFrom:
              configMapKeyRef:
                name: auth
                key: oauth.provider.endpoint.token
          - name: AUTH_OAUTH_PROVIDER_ENDPOINT_LOGOUT
            valueFrom:
              configMapKeyRef:
                name: auth
                key: oauth.provider.endpoint.logout
          - name: AUTH_SERVICEACCOUNT_PRIVATEKEY
            valueFrom:
              secretKeyRef:
                name: auth
                key: serviceaccount.privatekey
          - name: AUTH_SERVICEACCOUNT_PRIVATEKEYID
            valueFrom:
              secretKeyRef:
                name: auth
                key: serviceaccount.privatekeyid
          - name: AUTH_USERACCOUNT_PRIVATEKEY
            valueFrom:
              secretKeyRef:
                name: auth
                key: useraccount.privatekey
          - name: AUTH_USERACCOUNT_PRIVATEKEYID
            valueFrom:
              secretKeyRef:
                name: auth
                key: useraccount.privatekeyid
          - name: AUTH_GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth
                key: github.client.id
          - name: AUTH_GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth
                key: github.client.secret
          - name: AUTH_SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: auth
                key: sentry.dsn
          - name: AUTH_OSO_CLIENT_APIURL
            valueFrom:
              secretKeyRef:
                name: auth
                key: oso.client.apiurl
          - name: AUTH_TENANT_SERVICEURL
            valueFrom:
              secretKeyRef:
                name: auth
                key: tenantsvc.url
          - name: AUTH_OSO_REGAPP_SERVICEURL
            valueFrom:
              secretKeyRef:
                name: auth
                key: oso.regapp.url
          - name: AUTH_OSO_REGAPP_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth
                key: oso.regapp.admin.username
          - name: AUTH_OSO_REGAPP_ADMIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: auth
                key: oso.regapp.admin.token
          - name: AUTH_POSTGRES_SSLMODE
            valueFrom:
              configMapKeyRef:
                name: auth
                key: postgres.sslmode
          - name: AUTH_POSTGRES_CONNECTION_MAXIDLE
            valueFrom:
              configMapKeyRef:
                name: auth
                key: postgres.connection.maxidle
          - name: AUTH_POSTGRES_CONNECTION_MAXOPEN
            valueFrom:
              configMapKeyRef:
                name: auth
                key: postgres.connection.maxopen
          - name: AUTH_NOTAPPROVED_REDIRECT
            valueFrom:
              configMapKeyRef:
                name: auth
                key: notapproved_redirect
          - name: AUTH_REDIRECT_VALID
            valueFrom:
              configMapKeyRef:
                name: auth
                key: redirect.valid
          - name: AUTH_NOTIFICATION_SERVICEURL
            valueFrom:
              configMapKeyRef:
                name: auth
                key: notification.serviceurl
          - name: AUTH_EMAIL_VERIFY_URL
            valueFrom:
              configMapKeyRef:
                name: auth
                key: email.verify.url
          - name: AUTH_INVITATION_ACCEPTED_URL
            valueFrom:
              configMapKeyRef:
                name: auth
                key: invitation.accepted.url
          - name: AUTH_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: auth
                key: environment
          - name: AUTH_IGNORE_EMAIL_PROD
            valueFrom:
              configMapKeyRef:
                name: auth
                key: ignore.email.prod          
          - name: AUTH_USER_DEACTIVATION_NOTIFICATION_ENABLED
            valueFrom:
              configMapKeyRef:
                name: auth
                key: user.deactivation.notification.enabled
          - name: AUTH_USER_DEACTIVATION_ENABLED
            valueFrom:
              configMapKeyRef:
                name: auth
                key: user.deactivation.enabled
          - name: AUTH_USER_DEACTIVATION_FETCH_LIMIT
            valueFrom:
              configMapKeyRef:
                name: auth
                key: user.deactivation.fetch.limit
          - name: AUTH_USER_DEACTIVATION_NOTIFICATION_INTERVAL_SECONDS
            valueFrom:
              configMapKeyRef:
                name: auth
                key: user.deactivation.notification.interval.seconds
          - name: AUTH_USER_DEACTIVATION_INTERVAL_SECONDS
            valueFrom:
              configMapKeyRef:
                name: auth
                key: user.deactivation.interval.seconds
          imagePullPolicy: Always
          name: auth
          ports:
          - containerPort: 8089
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8089
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8089
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 0.1m
              memory: 10Mi
            limits:
              cpu: 400m
              memory: 1.5Gi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /etc/fabric8/
            name: auth-configs
            readOnly: true
        volumes:
        - name: auth-configs
          secret:
            secretName: auth-config-files
            items:
            - key: service.account.secrets
              path: service-account-secrets.conf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    details:
      causes:
      - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: auth
    labels:
      service: auth
  spec:
    ports:
      - name: "8089"
        protocol: TCP
        port: 80
        targetPort: 8089
    selector:
      service: auth
    type: ClusterIP
    sessionAffinity: null
parameters:
- name: IMAGE
  value: quay.io/openshiftio/rhel-fabric8-services-fabric8-auth
- name: IMAGE_TAG
  value: latest
- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: '1'
